<?php
define('CUSTOM_HELPSCOUT_EMAIL', 'support@creativeg.gr');
define('CUSTOM_HELPSOUCT_USERENGAGE_API_KEY', 'QB2gESzIXGJAHNw8PVPRXEAf0lujKGdbXgqjXTbI76Q2VOfO44ehbj2ShzKgvlgN');
define('CUSTOM_HELPSOUCT_USERENGAGE_ADMIN_ID', 'Xuyq7D');
define('CUSTOM_HELPSCOUT_SIGNATURE', 'rSPqYHmN4KsGxmY4roNKAEttDz9ZaHBfv8Ln4t1v');
