<?php
define('CUSTOM_HELPSCOUT_SECRET_KEY', 'rSPqYHmN4KsGxmY4roNKAEttDz9ZaHBfv8Ln4t1v');
define('CUSTOM_HELPSCOUT_EMAIL', 'support@creativeg.gr');
define('CUSTOM_HELPSCOUT_SUPPORT_API_KEY', '245f8b550acb2bb73bb61e8d5f19752ca4ea83a8');
define('CUSTOM_HELPSOUCT_USERENGAGE_API_KEY', 'QB2gESzIXGJAHNw8PVPRXEAf0lujKGdbXgqjXTbI76Q2VOfO44ehbj2ShzKgvlgN');
define('CUSTOM_HELPSOUCT_USERENGAGE_REDIRECT_PAGE', 'testhu');
define('CUSTOM_HELPSOUCT_USERENGAGE_ADMIN_ID', 'Xuyq7D');
